### ISSUE TITLE
Incorporate cytominer-eval

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/profiling-resistance-mechanisms#84]
With an update to pycytominer@02ed6647a0913e9f0b28cbafa97766d55eeffd20, we can no longer rely on the `audit` function.

```python
Traceback (most recent call last):
  File "generate-profiles.py", line 11, in <module>
    from scripts.profile_util import process_profile, load_config
  File "/home/ubuntu/efs/2018_05_30_ResistanceMechanisms_Kapoor/workspace/software/2018_05_30_ResistanceMechanisms_Kapoor/0.generate-profiles/scripts/profile_util.py", line 10, in <module>
    from pycytominer import (
ImportError: cannot import name 'audit' from 'pycytominer' (/home/ubuntu/miniconda3/envs/resistance-mechanisms/lib/python3.7/site-packages/pycytominer/__init__.py)
```

I need to incorporate `cytominer-eval` into the automated processing pipeline.

**Comment by gwaygenomics** [comment]
closed via #87
